version: '3.8'

networks:
  Tornado:
    driver: bridge

services:
  mysqld:
    container_name: mysqld
    image: mysql:8.0.27
    restart: on-failure
    networks:
      - Tornado
    ports:
      - 3360:3306
    environment:
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Tornado
  app:
    depends_on:
      - mysqld
    build: .
    restart: on-failure
    ports:
      - 8082:8080
    networks:
      - Tornado
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysqld
      DB_DATABASE: Tornado_keycloak
      DB_USER: root
      DB_PASSWORD: root
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: root
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "connectTimeout=30000"
    ports:
      - 8090:8080
    depends_on:
      - mysqld
    networks:
      - Tornado
volumes:
  data-volume: null
